-- Supabase SQL Editor でこのまま実行する
--
-- ============================================================
-- 重要: このファイルは production ブランチのコード(index.html)が
-- 実際に参照している shops / qr_routes テーブルの定義を、コードの
-- クエリ内容から逆算して再構成したものです。
-- 現在Supabase側に既にこれらのテーブルが存在する場合、実際のカラム
-- 構成と異なる可能性があります。実行前に必ずSupabaseダッシュボード
-- の Table Editor で既存の shops / qr_routes の定義と見比べてください。
-- 既存テーブルがある場合は create table 部分は無視され(if not exists)、
-- RLSポリシー部分だけが更新されます。
-- ============================================================

-- ---------------------------------------------------------
-- events テーブル(既存)
-- 変更点1: instagram_click / website_click を event_type に追加
-- 変更点2: RLSは一旦現状維持(insertはanon許可のまま/selectもanon許可のまま)
--          ※ selectの公開範囲はユーザー判断により今回は変更しません。
--            試験運用中の既知リスクとして受け入れています。
-- ---------------------------------------------------------
create table if not exists public.events (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  event_type text not null,
  hotel_id text,
  hotel_name text,
  shop_id text,
  shop_name text,
  slot text,
  edition text,
  qr_id text,
  user_agent text,
  page_url text
);

alter table public.events enable row level security;

-- event_type の許可値を実際にコードが送信する8種類に更新
alter table public.events drop constraint if exists events_event_type_check;
alter table public.events add constraint events_event_type_check
  check (
    event_type in (
      'qr_scan',
      'page_view',
      'reserve_click',
      'map_click',
      'phone_click',
      'coupon_view',
      'instagram_click',
      'website_click'
    )
  );

drop policy if exists "demo_allow_public_insert_events" on public.events;
create policy "demo_allow_public_insert_events"
on public.events
for insert
to anon
with check (true);

drop policy if exists "demo_allow_public_read_events" on public.events;
create policy "demo_allow_public_read_events"
on public.events
for select
to anon
using (true);


-- ---------------------------------------------------------
-- shops テーブル(コードから逆算した推定定義)
-- index.html が select しているカラム:
--   id, status, enabled, media, content, actions, coupon, hotel_overrides
-- ---------------------------------------------------------
create table if not exists public.shops (
  id text primary key,
  status text not null default 'draft' check (status in ('draft','published','archived')),
  enabled boolean not null default true,
  media jsonb not null default '{}'::jsonb,
  content jsonb not null default '{}'::jsonb,
  actions jsonb not null default '{}'::jsonb,
  coupon jsonb not null default '{}'::jsonb,
  hotel_overrides jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

alter table public.shops enable row level security;

-- 一般利用者(anon)は「公開済み・有効」な行だけ読める。書き込みは一切許可しない。
drop policy if exists "public_read_published_shops" on public.shops;
create policy "public_read_published_shops"
on public.shops
for select
to anon
using (status = 'published' and enabled = true);

-- anonによるinsert/update/deleteのポリシーは意図的に作成しません。
-- 店舗の追加・編集はSupabaseダッシュボード、またはservice_role権限
-- (サーバーサイドのみ)から行ってください。


-- ---------------------------------------------------------
-- qr_routes テーブル(コードから逆算した推定定義)
-- index.html が select しているカラム:
--   qr_code, hotel_id, shop_id, slot, edition, enabled
-- ---------------------------------------------------------
create table if not exists public.qr_routes (
  qr_code text primary key,
  hotel_id text not null,
  shop_id text not null,
  slot text,
  edition text,
  enabled boolean not null default true,
  created_at timestamp with time zone default now()
);

alter table public.qr_routes enable row level security;

-- 一般利用者(anon)は有効なQRコードの行だけ読める。書き込みは一切許可しない。
drop policy if exists "public_read_enabled_qr_routes" on public.qr_routes;
create policy "public_read_enabled_qr_routes"
on public.qr_routes
for select
to anon
using (enabled = true);

-- anonによるinsert/update/deleteのポリシーは意図的に作成しません。
-- QRコードの発行・無効化はSupabaseダッシュボード、またはservice_role
-- 権限(サーバーサイドのみ)から行ってください。
