-- Supabase SQL Editor でこのまま実行する
-- デモ用: anon に insert/select を許可しています。
-- 本番では管理画面閲覧に認証を入れるなど、RLSポリシーを絞ってください。

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  event_type text not null check (
    event_type in (
      'qr_scan',
      'page_view',
      'reserve_click',
      'map_click',
      'phone_click',
      'coupon_view'
    )
  ),
  hotel_id text,
  hotel_name text,
  shop_id text,
  shop_name text,
  slot text,
  edition text,
  qr_id text,
  user_agent text,
  page_url text
);

alter table public.events enable row level security;

drop policy if exists "demo_allow_public_insert_events" on public.events;
create policy "demo_allow_public_insert_events"
on public.events
for insert
to anon
with check (true);

drop policy if exists "demo_allow_public_read_events" on public.events;
create policy "demo_allow_public_read_events"
on public.events
for select
to anon
using (true);
